[build]
	publish = "dist"
	command = "npm run build"

[[headers]]
	# Define which paths this specific [[headers]] block will cover.
	for = "/*"

	[headers.values]
		Access-Control-Allow-Origin = "*"

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 0.8
		accessibility = 0.9
		best-practices = 0.8
		seo = 0.9

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"


